# Generated by Django 4.2.1 on 2023-05-07 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_author_alter_editorial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titulo')),
                ('isd', models.CharField(max_length=50, verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Pricio')),
                ('edition', models.CharField(max_length=50, verbose_name='Edicion')),
                ('numPages', models.PositiveIntegerField(verbose_name='Numero de páginas')),
                ('pubYear', models.CharField(max_length=4, verbose_name='Año de publicación')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.author', verbose_name='Autor')),
                ('editorial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.editorial', verbose_name='Edirorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
            },
        ),
    ]
